import JSZip from "jszip";
import type { SkillPackage } from "./skill-generator";

const LICENSE = `Apache License
Version 2.0, January 2004
http://www.apache.org/licenses/

Copyright 2026 TraceForge contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
`;

export async function buildSkillZip(skillPackage: SkillPackage): Promise<Buffer> {
  const zip = new JSZip();
  const readme = `# ${skillPackage.skillName}

Generated by TraceForge.

Visual Evidence → Diagnosis → Reusable Agent Skill

This package contains a validated Agent Skill produced from a debugging incident.

## Contents

- \`skills/${skillPackage.skillName}/SKILL.md\`
- \`skills/${skillPackage.skillName}/references/troubleshooting.md\`
`;

  zip.file("README.md", readme);
  zip.file("LICENSE", LICENSE);

  for (const file of skillPackage.files) {
    zip.file(file.path, file.content);
  }

  const bytes = await zip.generateAsync({ type: "nodebuffer" });
  return Buffer.from(bytes);
}
